### ISSUE TITLE
Not working on Scientific Linux release 6.6 (Carbon)

### ISSUE THREAD

**Issue by fsMarcoRouleau** [weslly/ColorPicker#80]
Whenever pressing "ok" I get this issue, and it looks like the colorPicker is not doing anything:

traceback (most recent call last):
  File "/PATH/TO/SUBLIME/Packages/ColorPicker/lib/linux_colorpicker.py", line 26, in <module>
    if color_sel.run() == getattr(Gtk, 'RESPONSE_OK', Gtk.ResponseType.OK):
AttributeError: type object 'ResponseType' has no attribute 'OK'

Removing the ".OK" from that line fixes it just fine. Anyway that was my quick workaround

**Comment by karelb** [comment]
Thanks. Works for me!

**Comment by tarpan** [comment]
You saved me from scrapping ST altogether! Many thanks.
